# Generated by Django 5.0.3 on 2024-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearn", "0002_assignments_course_student_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_materials",
            field=models.FileField(
                blank=True, null=True, upload_to="course_materials/"
            ),
        ),
    ]
