# Generated by Django 5.0.3 on 2024-03-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearn", "0003_course_course_materials"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="course_materials/")),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_materials",
        ),
        migrations.AddField(
            model_name="course",
            name="course_materials",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="elearn.coursematerial"
            ),
        ),
    ]
