# Generated by Django 5.0.3 on 2024-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearn", "0004_coursematerial_remove_course_course_materials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_materials",
            field=models.ManyToManyField(blank=True, to="elearn.coursematerial"),
        ),
    ]
