# Generated by Django 5.0.3 on 2024-03-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearn", "0005_alter_course_course_materials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_materials",
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearn.course",
            ),
        ),
    ]
