# Generated by Django 5.0.3 on 2024-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearn", "0007_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="First_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Last_name",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photo/"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photo/"),
        ),
    ]
