# Generated by Django 5.0.3 on 2024-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearn", "0008_rename_first_name_student_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("status_message", models.TextField(default="Type in your status")),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Assignments",
        ),
    ]
